version: "3"

services:
  namenode:
    extends:
      file: docker-compose-standalone.yml
      service: namenode

  datanode:
    extends:
      file: docker-compose-standalone.yml
      service: datanode

  resourcemanager:
    extends:
      file: docker-compose-standalone.yml
      service: resourcemanager

  nodemanager1:
    extends:
      file: docker-compose-standalone.yml
      service: nodemanager1

  historyserver:
    extends:
      file: docker-compose-standalone.yml
      service: historyserver

  hbase:
    image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
    container_name: hbase
    hostname: me_docker
    volumes:
      - hbase_data:/hbase-data
      - hbase_zookeeper_data:/zookeeper-data
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 2888:2888
      - 3888:3888
      - 2181:2181
      - 38535:38535
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hbase-standalone.env

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hbase_data:
  hbase_zookeeper_data:
